// ─── Development-only OTP transport ─────────────────────────────────────
// Only ever selected by createOtpProvider() (see otpProvider.ts) when
// NODE_ENV === 'development' AND MSG91 is not configured — never in
// production, never as a silent fallback. It does not return the OTP
// through any API response; it only writes one clearly-marked log line so
// a developer can complete OTP verification locally without a real SMS
// provider. The OTP is never a hardcoded/predictable value — it is the
// same cryptographically random code generated by auth.service.ts for
// every request.

import type { FastifyBaseLogger } from 'fastify'
import type { OtpProvider } from './otpProvider.js'

export function createDevOtpProvider(logger: FastifyBaseLogger): OtpProvider {
  return {
    async sendOtp(phoneNumberNormalized, otp) {
      logger.warn(
        { phoneNumberNormalized, otp },
        '[DEV-ONLY OTP] No real SMS provider is configured — printed here for local testing only. ' +
          'Set MSG91_AUTH_KEY and MSG91_TEMPLATE_ID to send real SMS via MSG91.',
      )
    },
  }
}
